// ---------------------------------------------------------------------------
// Google pipeline provider ("google"):
//   1. Claude (planning LLM) writes the shot prompt (existing planning stage).
//   2. Gemini image model renders a photorealistic KEYFRAME for the shot —
//      this locks scene continuity (same hands, same tiny kitchen) before
//      any video is generated.
//   3. Veo (Gemini API, predictLongRunning) animates that keyframe into a
//      video WITH native audio (cooking sounds are generated by Veo itself).
//   4. The finished MP4 is re-hosted on fal storage so the browser can play
//      it and the fal ffmpeg merge stage can concatenate all shots.
// Poll-driven and durable like every other provider: submit returns an
// operation name; advanceProduction polls it until the clip is ready.
// Requires GEMINI_API_KEY (paid tier for Veo) and FAL_KEY (hosting + merge).
// ---------------------------------------------------------------------------
import { cleanEnv } from "@/lib/env";
import type { ProviderShotStatus, ShotInput, ShotResult, VideoProvider } from "./types";

const G_BASE = "https://generativelanguage.googleapis.com/v1beta";

function gHeaders() {
  return { "x-goog-api-key": cleanEnv("GEMINI_API_KEY") ?? "", "Content-Type": "application/json" };
}

async function gFetch(url: string, init?: RequestInit) {
  const res = await fetch(url, { ...init, headers: { ...gHeaders(), ...(init?.headers ?? {}) }, cache: "no-store" });
  if (!res.ok) {
    const body = await res.text().catch(() => "");
    throw new Error(`Google API HTTP ${res.status}: ${body.slice(0, 300)}`);
  }
  return res;
}

/** Step 2: photorealistic keyframe that pins the scene before video generation. */
async function generateKeyframe(input: ShotInput): Promise<{ data: string; mimeType: string } | null> {
  const model = cleanEnv("GOOGLE_IMAGE_MODEL") ?? "gemini-2.5-flash-image";
  try {
    const res = await gFetch(`${G_BASE}/models/${model}:generateContent`, {
      method: "POST",
      body: JSON.stringify({
        contents: [
          {
            parts: [
              {
                text:
                  `Photorealistic still keyframe (first frame of a video), vertical 9:16. ${input.prompt} ` +
                  `Absolutely avoid: ${input.negativePrompt}.`,
              },
            ],
          },
        ],
        generationConfig: { responseModalities: ["IMAGE"], imageConfig: { aspectRatio: "9:16" } },
      }),
    });
    const data = (await res.json()) as {
      candidates?: Array<{ content?: { parts?: Array<{ inlineData?: { mimeType?: string; data?: string } }> } }>;
    };
    const part = data.candidates?.[0]?.content?.parts?.find((p) => p.inlineData?.data);
    if (!part?.inlineData?.data) return null;
    return { data: part.inlineData.data, mimeType: part.inlineData.mimeType ?? "image/png" };
  } catch (err) {
    // Keyframe is an enhancement, not a hard dependency — fall back to
    // text-to-video and log why, so a keyframe outage never blocks shots.
    console.error("Gemini keyframe failed, falling back to text-to-video:", err);
    return null;
  }
}

/** Re-host bytes on fal storage so the browser and the merge stage can use a plain URL. */
async function uploadToFalStorage(bytes: Uint8Array, fileName: string, contentType: string): Promise<string> {
  const initiate = await fetch("https://rest.fal.ai/storage/upload/initiate?storage_type=fal-cdn-v3", {
    method: "POST",
    headers: { Authorization: `Key ${cleanEnv("FAL_KEY") ?? ""}`, "Content-Type": "application/json" },
    body: JSON.stringify({ content_type: contentType, file_name: fileName }),
    cache: "no-store",
  });
  if (!initiate.ok) {
    const body = await initiate.text().catch(() => "");
    throw new Error(`fal storage initiate HTTP ${initiate.status}: ${body.slice(0, 200)}`);
  }
  const { upload_url, file_url } = (await initiate.json()) as { upload_url: string; file_url: string };
  const put = await fetch(upload_url, { method: "PUT", headers: { "Content-Type": contentType }, body: bytes as unknown as BodyInit });
  if (!put.ok) throw new Error(`fal storage upload HTTP ${put.status}`);
  return file_url;
}

export class GoogleVeoProvider implements VideoProvider {
  readonly isMock = false;
  readonly configurationHint =
    "Set GEMINI_API_KEY (paid tier — Veo access) and FAL_KEY (clip hosting + merge). Optional: GOOGLE_VIDEO_MODEL, GOOGLE_IMAGE_MODEL.";
  private videoModel = cleanEnv("GOOGLE_VIDEO_MODEL") ?? "veo-3.1-fast-generate-preview";
  get name() {
    return `Google (Gemini keyframe → ${this.videoModel}, native audio)`;
  }
  get configured() {
    return Boolean(cleanEnv("GEMINI_API_KEY") && cleanEnv("FAL_KEY"));
  }

  async submitShot(input: ShotInput) {
    const keyframe = await generateKeyframe(input);
    const seconds = [4, 6, 8].reduce((best, d) => (Math.abs(d - input.seconds) < Math.abs(best - input.seconds) ? d : best), 8);
    const instance: Record<string, unknown> = { prompt: input.prompt };
    if (keyframe) instance.image = { bytesBase64Encoded: keyframe.data, mimeType: keyframe.mimeType };
    const res = await gFetch(`${G_BASE}/models/${this.videoModel}:predictLongRunning`, {
      method: "POST",
      body: JSON.stringify({
        instances: [instance],
        parameters: {
          aspectRatio: "9:16",
          durationSeconds: seconds,
          negativePrompt: input.negativePrompt,
        },
      }),
    });
    const data = (await res.json()) as { name?: string };
    if (!data.name) throw new Error("Veo returned no operation name");
    return { providerJobId: data.name };
  }

  async getShotStatus(operationName: string): Promise<ProviderShotStatus> {
    const res = await gFetch(`${G_BASE}/${operationName}`);
    const op = (await res.json()) as { done?: boolean; error?: { message?: string } };
    if (op.error) return { state: "failed", error: `Veo: ${op.error.message ?? "generation error"}` };
    if (!op.done) return { state: "generating" };
    return { state: "completed" };
  }

  async getShotResult(operationName: string): Promise<ShotResult> {
    const res = await gFetch(`${G_BASE}/${operationName}`);
    const op = (await res.json()) as {
      response?: {
        generateVideoResponse?: { generatedSamples?: Array<{ video?: { uri?: string } }> };
        generatedVideos?: Array<{ video?: { uri?: string } }>;
      };
    };
    const uri =
      op.response?.generateVideoResponse?.generatedSamples?.[0]?.video?.uri ??
      op.response?.generatedVideos?.[0]?.video?.uri;
    if (!uri) throw new Error("Veo returned no video URI");

    // Download from Google (key-gated URI) and re-host on fal storage.
    const dl = await gFetch(uri);
    const bytes = new Uint8Array(await dl.arrayBuffer());
    const url = await uploadToFalStorage(bytes, `minibites_${Date.now().toString(36)}.mp4`, "video/mp4");
    return { videoUrl: url };
  }

  async cancelShot(operationName: string) {
    // The Gemini API long-running video operations do not expose a cancel
    // endpoint via API key; the pipeline simply stops polling.
    void operationName;
  }
}
